"""Add start_time and end_time to desk_bookings

Revision ID: 3d4f639d40d0
Revises: 72c51ceb3a4c
Create Date: 2026-02-22 16:29:42.688407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d4f639d40d0'
down_revision: Union[str, None] = '72c51ceb3a4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('desk_bookings', sa.Column('start_time', sa.Time(), server_default='09:00:00', nullable=False))
    op.add_column('desk_bookings', sa.Column('end_time', sa.Time(), server_default='18:00:00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('desk_bookings', 'end_time')
    op.drop_column('desk_bookings', 'start_time')
    # ### end Alembic commands ###
