"""drop_admin_type_column

Revision ID: 5c1a6edf8a08
Revises: 63e99d1fb461
Create Date: 2026-02-10 12:28:57.349563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c1a6edf8a08'
down_revision: Union[str, None] = '63e99d1fb461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_admin_type', table_name='users')
    op.drop_column('users', 'admin_type')
    # Note: Keeping user_code unique constraint
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin_type', postgresql.ENUM('IT', 'SECURITY', 'CAFETERIA', 'DESK', name='admintype'), autoincrement=False, nullable=True))
    op.create_index('ix_users_admin_type', 'users', ['admin_type'], unique=False)
    # ### end Alembic commands ###
