"""initial_migration_with_hierarchy

Revision ID: 63e99d1fb461
Revises: 
Create Date: 2026-02-10 12:01:05.276721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63e99d1fb461'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('it_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('asset_type', sa.Enum('LAPTOP', 'DESKTOP', 'MONITOR', 'KEYBOARD', 'MOUSE', 'HEADSET', 'WEBCAM', 'DOCKING_STATION', 'MOBILE_PHONE', 'TABLET', 'PRINTER', 'SCANNER', 'OTHER', name='assettype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('serial_number', sa.String(length=200), nullable=True),
    sa.Column('specifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('warranty_expiry', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'ASSIGNED', 'MAINTENANCE', 'RETIRED', name='assetstatus'), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index(op.f('ix_it_assets_asset_code'), 'it_assets', ['asset_code'], unique=True)
    op.create_index('ix_it_assets_available', 'it_assets', ['status', 'is_active'], unique=False)
    op.create_index('ix_it_assets_status', 'it_assets', ['status'], unique=False)
    op.create_index('ix_it_assets_type', 'it_assets', ['asset_type'], unique=False)
    op.create_table('leave_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.Enum('SICK', 'CASUAL', 'ANNUAL', 'UNPAID', 'MATERNITY', 'PATERNITY', 'BEREAVEMENT', name='leavetype'), nullable=False),
    sa.Column('default_days', sa.Integer(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('can_carry_forward', sa.Boolean(), nullable=True),
    sa.Column('max_carry_forward_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_code', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'MANAGER', 'TEAM_LEAD', 'EMPLOYEE', name='userrole'), nullable=False),
    sa.Column('manager_type', sa.Enum('PARKING', 'ATTENDANCE', 'DESK_CONFERENCE', 'CAFETERIA', 'IT_SUPPORT', name='managertype'), nullable=True),
    sa.Column('admin_type', sa.Enum('IT', 'SECURITY', 'CAFETERIA', 'DESK', name='admintype'), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('created_by_code', sa.String(length=10), nullable=True),
    sa.Column('team_lead_code', sa.String(length=10), nullable=True),
    sa.Column('manager_code', sa.String(length=10), nullable=True),
    sa.Column('admin_code', sa.String(length=10), nullable=True),
    sa.Column('vehicle_number', sa.String(length=50), nullable=True),
    sa.Column('vehicle_type', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_code')
    )
    op.create_index('ix_users_active_deleted', 'users', ['is_active', 'is_deleted'], unique=False)
    op.create_index('ix_users_admin', 'users', ['admin_code'], unique=False)
    op.create_index('ix_users_admin_type', 'users', ['admin_type'], unique=False)
    op.create_index('ix_users_created_by', 'users', ['created_by_code'], unique=False)
    op.create_index('ix_users_department', 'users', ['department'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_manager', 'users', ['manager_code'], unique=False)
    op.create_index('ix_users_manager_type', 'users', ['manager_type'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_users_team_lead', 'users', ['team_lead_code'], unique=False)
    op.create_index(op.f('ix_users_user_code'), 'users', ['user_code'], unique=True)
    # Add self-referential foreign keys after the unique constraint is created
    op.create_foreign_key('fk_users_admin_code', 'users', 'users', ['admin_code'], ['user_code'])
    op.create_foreign_key('fk_users_created_by_code', 'users', 'users', ['created_by_code'], ['user_code'])
    op.create_foreign_key('fk_users_manager_code', 'users', 'users', ['manager_code'], ['user_code'])
    op.create_foreign_key('fk_users_team_lead_code', 'users', 'users', ['team_lead_code'], ['user_code'])
    op.create_table('attendances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_code', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', name='attendancestatus'), nullable=True),
    sa.Column('first_check_in', sa.Time(), nullable=True),
    sa.Column('last_check_out', sa.Time(), nullable=True),
    sa.Column('total_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('approved_by_code', sa.String(length=10), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_code'], ['users.user_code'], ),
    sa.ForeignKeyConstraint(['user_code'], ['users.user_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attendance_date', 'attendances', ['date'], unique=False)
    op.create_index('ix_attendance_status', 'attendances', ['status'], unique=False)
    op.create_index('ix_attendance_user_date', 'attendances', ['user_code', 'date'], unique=True)
    op.create_table('floor_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('floor_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('plan_type', sa.Enum('PARKING', 'DESK_AREA', 'CAFETERIA', name='floorplantype'), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('columns', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=True),
    sa.Column('created_by_code', sa.String(length=10), nullable=False),
    sa.Column('building_name', sa.String(length=100), nullable=True),
    sa.Column('floor_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_code'], ['users.user_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_floor_plans_active_type', 'floor_plans', ['is_active', 'plan_type'], unique=False)
    op.create_index('ix_floor_plans_code', 'floor_plans', ['floor_code'], unique=False)
    op.create_index(op.f('ix_floor_plans_floor_code'), 'floor_plans', ['floor_code'], unique=True)
    op.create_index('ix_floor_plans_type', 'floor_plans', ['plan_type'], unique=False)
    op.create_table('food_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ingredients', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('allergens', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_special', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('preparation_time_minutes', sa.Integer(), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('created_by_code', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['food_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by_code'], ['users.user_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_food_items_available', 'food_items', ['is_available', 'is_active'], unique=False)
    op.create_index('ix_food_items_category', 'food_items', ['category_id'], unique=False)
    op.create_index('ix_food_items_special', 'food_items', ['is_special'], unique=False)
    op.create_table('food_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('user_code', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PREPARING', 'READY', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('scheduled_time', sa.Time(), nullable=True),
    sa.Column('is_scheduled', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preparing_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('processed_by_code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['processed_by_code'], ['users.user_code'], ),
    sa.ForeignKeyConstraint(['user_code'], ['users.user_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_food_orders_date', 'food_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_food_orders_order_number'), 'food_orders', ['order_number'], unique=True)
    op.create_index('ix_food_orders_scheduled', 'food_orders', ['scheduled_date', 'scheduled_time'], unique=False)
    op.create_index('ix_food_orders_user_status', 'food_orders', ['user_code', 'status'], unique=False)
    op.create_table('it_asset_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('user_code', sa.String(length=10), nullable=False),
    sa.Column('assigned_by_code', sa.String(length=10), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_to_code', sa.String(length=10), nullable=True),
    sa.Column('return_condition', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledgement_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['it_assets.id'], ),
    sa.ForeignKeyConstraint(['assigned_by_code'], ['users.user_code'], ),
    sa.ForeignKeyConstraint(['returned_to_code'], ['users.user_code'], ),
    sa.ForeignKeyConstraint(['user_code'], ['users.user_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_asset_assignment_active', 'it_asset_assignments', ['asset_id', 'is_active'], unique=False)
    op.create_index('ix_asset_assignment_user', 'it_asset_assignments', ['user_code', 'is_active'], unique=False)
    op.create_table('it_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_number', sa.String(length=50), nullable=False),
    sa.Column('user_code', sa.String(length=10), nullable=False),
    sa.Column('request_type', sa.Enum('REPAIR', 'REPLACEMENT', 'NEW', name='itrequesttype'), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='itrequestpriority'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', name='itrequeststatus'), nullable=True),
    sa.Column('approved_by_code', sa.String(length=10), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('assigned_to_code', sa.String(length=10), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('in_progress_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by_code', sa.String(length=10), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_code'], ['users.user_code'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['it_assets.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_code'], ['users.user_code'], ),
    sa.ForeignKeyConstraint(['rejected_by_code'], ['users.user_code'], ),
    sa.ForeignKeyConstraint(['user_code'], ['users.user_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_it_request_assigned', 'it_requests', ['assigned_to_code', 'status'], unique=False)
    op.create_index('ix_it_request_priority', 'it_requests', ['priority'], unique=False)
    op.create_index('ix_it_request_status', 'it_requests', ['status'], unique=False)
    op.create_index('ix_it_request_type', 'it_requests', ['request_type'], unique=False)
    op.create_index('ix_it_request_user', 'it_requests', ['user_code'], unique=False)
    op.create_index(op.f('ix_it_requests_request_number'), 'it_requests', ['request_number'], unique=True)
    op.create_table('leave_balances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_code', sa.String(length=10), nullable=False),
    sa.Column('leave_type_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('used_days', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('pending_days', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.ForeignKeyConstraint(['user_code'], ['users.user_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leave_balance_unique', 'leave_balances', ['user_code', 'leave_type_id', 'year'], unique=True)
    op.create_table('leave_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_code', sa.String(length=10), nullable=False),
    sa.Column('leave_type_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('is_half_day', sa.Boolean(), nullable=True),
    sa.Column('half_day_type', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED_BY_TEAM_LEAD', 'APPROVED', 'REJECTED', 'CANCELLED', name='leavestatus'), nullable=True),
    sa.Column('level1_approver_code', sa.String(length=10), nullable=True),
    sa.Column('level1_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('level1_notes', sa.Text(), nullable=True),
    sa.Column('final_approver_code', sa.String(length=10), nullable=True),
    sa.Column('final_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_approval_notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('rejected_by_code', sa.String(length=10), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('emergency_contact', sa.String(length=100), nullable=True),
    sa.Column('emergency_phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['final_approver_code'], ['users.user_code'], ),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.ForeignKeyConstraint(['level1_approver_code'], ['users.user_code'], ),
    sa.ForeignKeyConstraint(['rejected_by_code'], ['users.user_code'], ),
    sa.ForeignKeyConstraint(['user_code'], ['users.user_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leave_request_dates', 'leave_requests', ['start_date', 'end_date'], unique=False)
    op.create_index('ix_leave_request_status', 'leave_requests', ['status'], unique=False)
    op.create_index('ix_leave_request_user', 'leave_requests', ['user_code', 'start_date'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requested_by_code', sa.String(length=10), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='projectstatus'), nullable=True),
    sa.Column('approved_by_code', sa.String(length=10), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_code'], ['users.user_code'], ),
    sa.ForeignKeyConstraint(['requested_by_code'], ['users.user_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_requested_by', 'projects', ['requested_by_code'], unique=False)
    op.create_index('ix_project_status', 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_project_code'), 'projects', ['project_code'], unique=True)
    op.create_table('attendance_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attendance_id', sa.UUID(), nullable=False),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_type', sa.String(length=50), nullable=True),
    sa.Column('duration_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cafeteria_tables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('floor_plan_id', sa.UUID(), nullable=False),
    sa.Column('table_code', sa.String(length=20), nullable=False),
    sa.Column('table_label', sa.String(length=50), nullable=False),
    sa.Column('cell_row', sa.Integer(), nullable=False),
    sa.Column('cell_column', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('table_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['floor_plan_id'], ['floor_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cafeteria_tables_capacity', 'cafeteria_tables', ['capacity'], unique=False)
    op.create_index('ix_cafeteria_tables_floor', 'cafeteria_tables', ['floor_plan_id'], unique=False)
    op.create_index(op.f('ix_cafeteria_tables_table_code'), 'cafeteria_tables', ['table_code'], unique=True)
    op.create_table('conference_rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('floor_plan_id', sa.UUID(), nullable=False),
    sa.Column('room_code', sa.String(length=20), nullable=False),
    sa.Column('room_name', sa.String(length=100), nullable=False),
    sa.Column('cell_row', sa.Integer(), nullable=False),
    sa.Column('cell_column', sa.Integer(), nullable=False),
    sa.Column('cell_span_rows', sa.Integer(), nullable=True),
    sa.Column('cell_span_cols', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('has_projector', sa.Boolean(), nullable=True),
    sa.Column('has_whiteboard', sa.Boolean(), nullable=True),
    sa.Column('has_video_conference', sa.Boolean(), nullable=True),
    sa.Column('has_phone', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'BOOKED', 'MAINTENANCE', 'DISABLED', name='deskstatus'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['floor_plan_id'], ['floor_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conference_rooms_capacity', 'conference_rooms', ['capacity'], unique=False)
    op.create_index('ix_conference_rooms_floor', 'conference_rooms', ['floor_plan_id'], unique=False)
    op.create_index(op.f('ix_conference_rooms_room_code'), 'conference_rooms', ['room_code'], unique=True)
    op.create_table('desks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('floor_plan_id', sa.UUID(), nullable=False),
    sa.Column('desk_code', sa.String(length=20), nullable=False),
    sa.Column('desk_label', sa.String(length=50), nullable=False),
    sa.Column('cell_row', sa.Integer(), nullable=False),
    sa.Column('cell_column', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'BOOKED', 'MAINTENANCE', 'DISABLED', name='deskstatus'), nullable=True),
    sa.Column('has_monitor', sa.Boolean(), nullable=True),
    sa.Column('has_docking_station', sa.Boolean(), nullable=True),
    sa.Column('zone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['floor_plan_id'], ['floor_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desks_desk_code'), 'desks', ['desk_code'], unique=True)
    op.create_index('ix_desks_floor', 'desks', ['floor_plan_id'], unique=False)
    op.create_index('ix_desks_status', 'desks', ['status'], unique=False)
    op.create_index('ix_desks_zone', 'desks', ['zone'], unique=False)
    op.create_table('floor_plan_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('floor_plan_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('grid_data', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by_code', sa.String(length=10), nullable=False),
    sa.Column('change_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_code'], ['users.user_code'], ),
    sa.ForeignKeyConstraint(['floor_plan_id'], ['floor_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_floor_plan_versions_unique', 'floor_plan_versions', ['floor_plan_id', 'version'], unique=True)
    op.create_table('food_order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('food_item_id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['food_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parking_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('floor_plan_id', sa.UUID(), nullable=False),
    sa.Column('slot_code', sa.String(length=20), nullable=False),
    sa.Column('slot_label', sa.String(length=50), nullable=False),
    sa.Column('cell_row', sa.Integer(), nullable=False),
    sa.Column('cell_column', sa.Integer(), nullable=False),
    sa.Column('parking_type', sa.Enum('EMPLOYEE', 'VISITOR', name='parkingtype'), nullable=False),
    sa.Column('vehicle_type', sa.Enum('CAR', 'BIKE', 'TWO_WHEELER', name='vehicletype'), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'OCCUPIED', 'DISABLED', 'MAINTENANCE', name='parkingslotstatus'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['floor_plan_id'], ['floor_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_parking_slots_floor', 'parking_slots', ['floor_plan_id'], unique=False)
    op.create_index(op.f('ix_parking_slots_slot_code'), 'parking_slots', ['slot_code'], unique=True)
    op.create_index('ix_parking_slots_status', 'parking_slots', ['status'], unique=False)
    op.create_table('project_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_code', sa.String(length=10), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_code'], ['users.user_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_member_unique', 'project_members', ['project_id', 'user_code'], unique=True)
    op.create_index('ix_project_member_user', 'project_members', ['user_code', 'is_active'], unique=False)
    op.create_table('cafeteria_table_bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.Column('user_code', sa.String(length=10), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('guest_count', sa.Integer(), nullable=True),
    sa.Column('guest_names', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'NO_SHOW', name='bookingstatus'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['cafeteria_tables.id'], ),
    sa.ForeignKeyConstraint(['user_code'], ['users.user_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_table_booking_date', 'cafeteria_table_bookings', ['table_id', 'booking_date'], unique=False)
    op.create_index('ix_table_booking_status', 'cafeteria_table_bookings', ['status'], unique=False)
    op.create_index('ix_table_booking_user', 'cafeteria_table_bookings', ['user_code', 'booking_date'], unique=False)
    op.create_table('conference_room_bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('user_code', sa.String(length=10), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('attendees_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'NO_SHOW', name='bookingstatus'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['conference_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_code'], ['users.user_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conf_booking_date', 'conference_room_bookings', ['room_id', 'booking_date'], unique=False)
    op.create_index('ix_conf_booking_status', 'conference_room_bookings', ['status'], unique=False)
    op.create_index('ix_conf_booking_user', 'conference_room_bookings', ['user_code', 'booking_date'], unique=False)
    op.create_table('desk_bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('desk_id', sa.UUID(), nullable=False),
    sa.Column('user_code', sa.String(length=10), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'NO_SHOW', name='bookingstatus'), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['desk_id'], ['desks.id'], ),
    sa.ForeignKeyConstraint(['user_code'], ['users.user_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_desk_booking_date', 'desk_bookings', ['desk_id', 'booking_date'], unique=False)
    op.create_index('ix_desk_booking_status', 'desk_bookings', ['status'], unique=False)
    op.create_index('ix_desk_booking_user', 'desk_bookings', ['user_code', 'booking_date'], unique=False)
    op.create_table('parking_allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('user_code', sa.String(length=10), nullable=True),
    sa.Column('parking_type', sa.Enum('EMPLOYEE', 'VISITOR', name='parkingtype'), nullable=False),
    sa.Column('visitor_name', sa.String(length=200), nullable=True),
    sa.Column('visitor_phone', sa.String(length=20), nullable=True),
    sa.Column('visitor_company', sa.String(length=200), nullable=True),
    sa.Column('vehicle_number', sa.String(length=50), nullable=False),
    sa.Column('vehicle_type', sa.Enum('CAR', 'BIKE', 'TWO_WHEELER', name='vehicletype'), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['parking_slots.id'], ),
    sa.ForeignKeyConstraint(['user_code'], ['users.user_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_parking_allocation_entry', 'parking_allocations', ['entry_time'], unique=False)
    op.create_index('ix_parking_allocation_slot', 'parking_allocations', ['slot_id', 'is_active'], unique=False)
    op.create_index('ix_parking_allocation_user', 'parking_allocations', ['user_code', 'is_active'], unique=False)
    op.create_table('parking_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('allocation_id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('slot_code', sa.String(length=20), nullable=False),
    sa.Column('parking_type', sa.Enum('EMPLOYEE', 'VISITOR', name='parkingtype'), nullable=False),
    sa.Column('user_code', sa.String(length=10), nullable=True),
    sa.Column('visitor_name', sa.String(length=200), nullable=True),
    sa.Column('vehicle_number', sa.String(length=50), nullable=False),
    sa.Column('vehicle_type', sa.Enum('CAR', 'BIKE', 'TWO_WHEELER', name='vehicletype'), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['parking_slots.id'], ),
    sa.ForeignKeyConstraint(['user_code'], ['users.user_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_parking_history_date', 'parking_history', ['entry_time'], unique=False)
    op.create_index('ix_parking_history_slot', 'parking_history', ['slot_id'], unique=False)
    op.create_index('ix_parking_history_user', 'parking_history', ['user_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_parking_history_user', table_name='parking_history')
    op.drop_index('ix_parking_history_slot', table_name='parking_history')
    op.drop_index('ix_parking_history_date', table_name='parking_history')
    op.drop_table('parking_history')
    op.drop_index('ix_parking_allocation_user', table_name='parking_allocations')
    op.drop_index('ix_parking_allocation_slot', table_name='parking_allocations')
    op.drop_index('ix_parking_allocation_entry', table_name='parking_allocations')
    op.drop_table('parking_allocations')
    op.drop_index('ix_desk_booking_user', table_name='desk_bookings')
    op.drop_index('ix_desk_booking_status', table_name='desk_bookings')
    op.drop_index('ix_desk_booking_date', table_name='desk_bookings')
    op.drop_table('desk_bookings')
    op.drop_index('ix_conf_booking_user', table_name='conference_room_bookings')
    op.drop_index('ix_conf_booking_status', table_name='conference_room_bookings')
    op.drop_index('ix_conf_booking_date', table_name='conference_room_bookings')
    op.drop_table('conference_room_bookings')
    op.drop_index('ix_table_booking_user', table_name='cafeteria_table_bookings')
    op.drop_index('ix_table_booking_status', table_name='cafeteria_table_bookings')
    op.drop_index('ix_table_booking_date', table_name='cafeteria_table_bookings')
    op.drop_table('cafeteria_table_bookings')
    op.drop_index('ix_project_member_user', table_name='project_members')
    op.drop_index('ix_project_member_unique', table_name='project_members')
    op.drop_table('project_members')
    op.drop_index('ix_parking_slots_status', table_name='parking_slots')
    op.drop_index(op.f('ix_parking_slots_slot_code'), table_name='parking_slots')
    op.drop_index('ix_parking_slots_floor', table_name='parking_slots')
    op.drop_table('parking_slots')
    op.drop_table('food_order_items')
    op.drop_index('ix_floor_plan_versions_unique', table_name='floor_plan_versions')
    op.drop_table('floor_plan_versions')
    op.drop_index('ix_desks_zone', table_name='desks')
    op.drop_index('ix_desks_status', table_name='desks')
    op.drop_index('ix_desks_floor', table_name='desks')
    op.drop_index(op.f('ix_desks_desk_code'), table_name='desks')
    op.drop_table('desks')
    op.drop_index(op.f('ix_conference_rooms_room_code'), table_name='conference_rooms')
    op.drop_index('ix_conference_rooms_floor', table_name='conference_rooms')
    op.drop_index('ix_conference_rooms_capacity', table_name='conference_rooms')
    op.drop_table('conference_rooms')
    op.drop_index(op.f('ix_cafeteria_tables_table_code'), table_name='cafeteria_tables')
    op.drop_index('ix_cafeteria_tables_floor', table_name='cafeteria_tables')
    op.drop_index('ix_cafeteria_tables_capacity', table_name='cafeteria_tables')
    op.drop_table('cafeteria_tables')
    op.drop_table('attendance_entries')
    op.drop_index(op.f('ix_projects_project_code'), table_name='projects')
    op.drop_index('ix_project_status', table_name='projects')
    op.drop_index('ix_project_requested_by', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_leave_request_user', table_name='leave_requests')
    op.drop_index('ix_leave_request_status', table_name='leave_requests')
    op.drop_index('ix_leave_request_dates', table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index('ix_leave_balance_unique', table_name='leave_balances')
    op.drop_table('leave_balances')
    op.drop_index(op.f('ix_it_requests_request_number'), table_name='it_requests')
    op.drop_index('ix_it_request_user', table_name='it_requests')
    op.drop_index('ix_it_request_type', table_name='it_requests')
    op.drop_index('ix_it_request_status', table_name='it_requests')
    op.drop_index('ix_it_request_priority', table_name='it_requests')
    op.drop_index('ix_it_request_assigned', table_name='it_requests')
    op.drop_table('it_requests')
    op.drop_index('ix_asset_assignment_user', table_name='it_asset_assignments')
    op.drop_index('ix_asset_assignment_active', table_name='it_asset_assignments')
    op.drop_table('it_asset_assignments')
    op.drop_index('ix_food_orders_user_status', table_name='food_orders')
    op.drop_index('ix_food_orders_scheduled', table_name='food_orders')
    op.drop_index(op.f('ix_food_orders_order_number'), table_name='food_orders')
    op.drop_index('ix_food_orders_date', table_name='food_orders')
    op.drop_table('food_orders')
    op.drop_index('ix_food_items_special', table_name='food_items')
    op.drop_index('ix_food_items_category', table_name='food_items')
    op.drop_index('ix_food_items_available', table_name='food_items')
    op.drop_table('food_items')
    op.drop_index('ix_floor_plans_type', table_name='floor_plans')
    op.drop_index(op.f('ix_floor_plans_floor_code'), table_name='floor_plans')
    op.drop_index('ix_floor_plans_code', table_name='floor_plans')
    op.drop_index('ix_floor_plans_active_type', table_name='floor_plans')
    op.drop_table('floor_plans')
    op.drop_index('ix_attendance_user_date', table_name='attendances')
    op.drop_index('ix_attendance_status', table_name='attendances')
    op.drop_index('ix_attendance_date', table_name='attendances')
    op.drop_table('attendances')
    op.drop_index(op.f('ix_users_user_code'), table_name='users')
    op.drop_index('ix_users_team_lead', table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_manager_type', table_name='users')
    op.drop_index('ix_users_manager', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_users_department', table_name='users')
    op.drop_index('ix_users_created_by', table_name='users')
    op.drop_index('ix_users_admin_type', table_name='users')
    op.drop_index('ix_users_admin', table_name='users')
    op.drop_index('ix_users_active_deleted', table_name='users')
    op.drop_table('users')
    op.drop_table('leave_types')
    op.drop_index('ix_it_assets_type', table_name='it_assets')
    op.drop_index('ix_it_assets_status', table_name='it_assets')
    op.drop_index('ix_it_assets_available', table_name='it_assets')
    op.drop_index(op.f('ix_it_assets_asset_code'), table_name='it_assets')
    op.drop_table('it_assets')
    op.drop_table('food_categories')
    # ### end Alembic commands ###
