export const ROLES = {
    SUPER_ADMIN: 'SUPER_ADMIN',
    ADMIN: 'ADMIN',
    MANAGER: 'MANAGER',
    TEAM_LEAD: 'TEAM_LEAD',
    EMPLOYEE: 'EMPLOYEE',
    ATTENDANCE_MANAGER: 'ATTENDANCE_MANAGER',
    CAFETERIA_MANAGER: 'CAFETERIA_MANAGER',
    REPORTING_MANAGER: 'REPORTING_MANAGER',
    CONFERENCE_DESK_MANAGER: 'CONFERENCE_DESK_MANAGER'
};

export const MANAGER_TYPES = {
    PARKING: 'PARKING',
    IT_SUPPORT: 'IT_SUPPORT',
    ATTENDANCE: 'ATTENDANCE',
    CAFETERIA: 'CAFETERIA',
    DESK_CONFERENCE: 'DESK_CONFERENCE',
};
